### ISSUE TITLE
error "undefined method ::getCartProductShowPid()" since 3.4.0

### ISSUE THREAD

**Issue by HenryAveMedi** [extcode/cart_products#101]
I updated the cart and cart_products extensions
cart: 8.0.1
cart_products: 4.0.1
TYPO3: 10.4.21

And now I get the following error
in FE
---
Oops, an error occurred!
Call to undefined method TYPO3\CMS\Extbase\Domain\Model\Category::getCartProductShowPid()
---

in BE
---
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Extbase\Domain\Model\Category::getCartProductShowPid() | Error thrown in file typo3conf/ext/cart_products/Classes/ViewHelpers/Link/ProductViewHelper.php in line 49.
---

I tried to rollback version by version in cart_products… the last one that still works in my installation is 3.2.0 from 20-10-2021

turned off my templates, deleted chaces in maintainace module, and still getting errors…… don't know how to approach this or if someone else also has this error…… or if it's not compatible anymore with typo3 10 and it's not being properly blocked by the extensions module

Any idea?

**Comment by extcode** [comment]
I'll will replace the use-Statement in https://github.com/extcode/cart_products/blob/main/Classes/Domain/Model/Product/Product.php#L14. The Class should be `\Extcode\CartProducts\Domain\Model\Category`.

**Comment by rintisch** [comment]
I think this is solved? Will close it, but you're welcome to reopen if necessary!

Thanks for your input.
