### ISSUE TITLE
Default value needed

### ISSUE THREAD

**Issue by tobiasquadflieg** [extcode/cart_products#111]
TYPO3 Version 11.5.13
Webserver nginx/1.20.2
PHP Version 7.4.29
Database MySQL 5.5.5-10.3.34-MariaDB-1:10.3.34+maria~focal-log
cart_products v4.0.6

https://github.com/extcode/cart_products/blob/a203f135f1375e5d5e8aaf871ef5bc7dcc0bf0cd/Configuration/TCA/Overrides/pages.php#L40

'default' => 0

if you copy a page typo3 will throw a error 

 ``2: SQL error: 'Incorrect integer value: '' for column `db`.`pages`.`cart_products_product` at row 1' (pages:NEW62e783532401f328925358)``

**Comment by siwa-pparzer** [comment]
can confirm - error still in place

**Comment by hannesbochmann** [comment]
I can confirm this, too. Adding a default value in TCA fixes the problem.
