### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by worldwideweber** [extcode/cart_products#112]
TYPO3 Version 11.5.16
Webserver nginx/1.18.0
PHP Version 8.1.2
cart_products v4.0.6

Error:
PHP Warning: Undefined variable $product in /app/web/typo3conf/ext/cart_products/Classes/Controller/ProductController.php line 287

PHP Warning: Undefined array key "cart" in /app/web/typo3conf/ext/cart_products/Classes/Controller/ProductController.php line 298

The Extension works wit PHP 7.4 but not with PHP 8 or PHP 8.1

Since the End of Support for PHP 7.4 is near, it would be great to Support PHP 8.

**Comment by IL-Michi** [comment]
the problem still exists is there already a solution for this?

**Comment by peter-neumann-dev** [comment]
I can reproduce, this is still a bug.

**Comment by rintisch** [comment]
I do not get this error in v5.x-dev as the code is no longer existing. I think this can be closed!?

**Comment by rintisch** [comment]
Closed due to missing feedback.
