### ISSUE TITLE
Use the new Context API for TFSE data

### ISSUE THREAD

**Issue by tobiasquadflieg** [extcode/cart_products#114]
Replace the old TFSE-> calls with the new and easier way of the TYPO3 Context API.

E.g. :
https://github.com/extcode/cart_products/blob/a203f135f1375e5d5e8aaf871ef5bc7dcc0bf0cd/Classes/ViewHelpers/Product/AbstractProductViewHelper.php#L41-L58

https://github.com/extcode/cart_products/blob/a203f135f1375e5d5e8aaf871ef5bc7dcc0bf0cd/Classes/ViewHelpers/Product/IfBestSpecialPriceAvailableViewHelper.php#L53

```
    protected static function getFrontendUserGroupIds(): array
    {
        return GeneralUtility::makeInstance(Context::class)->getPropertyFromAspect('frontend.user', 'groupIds');
    }
```

**Comment by t3pwa** [comment]
With TYPO3 v11.5.21, cart 8.5.2, cart-products: 4.0.6

Exception: PHP Warning: Trying to access array offset on value of type null in /public/typo3conf/ext/cart_products/Classes/ViewHelpers/Product/IfBestSpecialPriceAvailableViewHelper.php line 56

$feUserId = (int)$GLOBALS['TSFE']->fe_user->user['uid'];

**Comment by t3pwa** [comment]
related: https://github.com/extcode/cart_products/issues/112
