### ISSUE TITLE
severity key is missing

### ISSUE THREAD

**Issue by TrueType** [extcode/cart_products#120]
https://github.com/extcode/cart_products/blob/8ca94e1c56d9e739f6086d4874a793e41a5306ca/Classes/EventListener/RetrieveProductsFromRequest.php#L74

comparing the two if blocks the second array is build differently

**Comment by TrueType** [comment]
ist for EXT:cart_books the same.

**Comment by TrueType** [comment]
These error messages are not processed at all? They should be instances of FlashMessage.

**Comment by rintisch** [comment]
Can you test whether the problem still exists in the latest version (branch `main`)?

**Comment by TrueType** [comment]
sry, I can not. I am not with the project and the customer any more.

**Comment by rintisch** [comment]
Thank you for the quick feedback! 

In this case I will close the issue. The code was refactored so it might be solved.
