### ISSUE TITLE
t3:link don't parsed when product has backend variants

### ISSUE THREAD

**Issue by webdev-pw** [extcode/cart_products#124]
Hello,
I updated TYPO3 9.5 to 11.5, since then product links from the RTE are no longer rendered in the frontend.
However, it only affects products that have "backend variants".
The products without "backend variants" works fine.
Does anyone have an idea what it could be?

TYPO3: 11.5.30
cart: 8.6.1
cart_products: 4.1.0

**Comment by extcode** [comment]
Do you have a solution for that? Can you provide a ddev container (or an other way for testing) and a description to debug the problem?

**Comment by rintisch** [comment]
@webdev-pw In which field in the backend do you enter the links that are not rendered?

**Comment by rintisch** [comment]
I will lose this issue because it works for me and we got no feedback. You're welcome to respond if you still have the problem.
