### ISSUE TITLE
Broken ViewHelper in Backend/List.html

### ISSUE THREAD

**Issue by ivgemeri** [extcode/cart_products#14]
Fluid parse error in template Backend\Product_action_list_1b65905ee2668598b4639c775a7e5ea94deb48dd, line 1 at character 1. Error: Unknown Namespace: products (error code 0).

Wrong Viewhelper declaration in Resources/Private/BAckend//V8//Templates/Backend/Product/List.html
....
      xmlns:cart="http://typo3.org/ns/Extcode/Cart/ViewHelpers"
      data-namespace-typo3-fluid="true">
changed in 
....
      xmlns:cart="http://typo3.org/ns/Extcode/CartProducts/ViewHelpers"
      data-namespace-typo3-fluid="true">

**Comment by extcode** [comment]
Can you give me some more information about this issue? Which version you use? Where does this fail?

**Comment by ivgemeri** [comment]
TYPO3 8.17
cart master Version 5.0.0
cart_products master 0.3.0

We have fixed the problem and changed the view helper reference from Extcode/Cart/ViewHelpers to Extcode/CartProducts/ViewHelpers in the source Templates/Backend/Product/List.html. 
The error occured, if you used the backend view Shopping Cart -> Products.
