### ISSUE TITLE
Return value must be of type ?Extcode\CartProducts\Domain\Model\Product\Product

### ISSUE THREAD

**Issue by tobiasquadflieg** [extcode/cart_products#150]
Seems like, $product needs to be initialized with $product = null, atm facing an issue where an exception is thrown, caused by the return type of the function.

```PHP
 protected function getProduct(): ?Product  {}
```

If $product isn't init as null and all conditions are false, $product is undefined and so it doesn't match the return type. Seems like a PHP return type thing.

Just init 
```PHP
$product = null; 
```
and all the problems are gone.

https://github.com/extcode/cart_products/blob/85a5a95dac80ae6408606e529bb8d26ecf6b80ca/Classes/Controller/ProductController.php#L235

**Comment by rintisch** [comment]
This seems to be solved for the coming v5, see
https://github.com/extcode/cart_products/blob/322807260014c4acb8ad0ca7bbad70e58d117c1f/Classes/Controller/ProductController.php#L232-L245

**Comment by rintisch** [comment]
@tobiasquadflieg Is it okay to close this issue or do you need it for v4?

**Comment by tobiasquadflieg** [comment]
would be great to fix this also in v4, because TYPO3 v11 Supports up to PHP8.3 so this might also happen to another user of v4.
