### ISSUE TITLE
wrong display of price

### ISSUE THREAD

**Issue by Hobokens** [extcode/cart_products#182]
## Bug Report

**Current Behavior**
I have a product with a price of €3.50. In the `list view` and in the `detailed view`, the price is shown as €4. However, on the page where all orders are displayed in the overview, the correct price, i.e. €3.50 is displayed.

**Expected behavior/output**
I expect to see the correct price in all views.

**Environment**
TYPO3 12.4.17
cart 9.0.0
cart_products 5.0.0 (from github)

- Is your TYPO3 installation set up with Composer?  no
- OS: Windows 10

**Possible Solution**
For the moment I solved the problem for me by replacing
```
cart:format.currency currencyTranslation="{currencyTranslationData.currencyTranslation}"
                      currencySign="{currencyTranslationData.currencySign}">{product.xxxxxx}</cart:format.currency>
```
with
`<f:format.currency>{product.xxxxxx}</f:format.currency>&nbsp;{currencyTranslationData.currencySign}`

**Comment by Hobokens** [comment]
In the logs in find the warning `Error handler (FE): PHP Warning: Undefined array key "format" in /var/www/html/vendor/extcode/cart/Classes/ViewHelpers/Format/CurrencyViewHelper.php line 111`

**Comment by rintisch** [comment]
I cannot reproduce this error. Can you make sure that your TypoScript is correct? See https://docs.typo3.org/p/extcode/cart/main/en-us/Administrator/Configuration/Currency/Index.html

**Comment by Hobokens** [comment]
I didn't do any currency settings for cart or cart_products in my sitepackage. I checked the active TypoScript in the backend and saw the necessary settings for the currency in the constants and the setup from the original extensions.

**Comment by rintisch** [comment]
@Hobokens 
Can you add `<f:debug>{currencyTranslationData}</f:debug>` in the views where it's not working and also where it's working and compare those to see whether it's the expected output?

**Comment by Hobokens** [comment]
Debugging `{currencyTranslationData}` in list view and detail view I get 

```
array(3 items)
   currencyCode => 'EUR' (3 chars)
   currencySign => '€' (1 chars)
   currencyTranslation => 1 (double)
```
Templates:
```
cart_products/Resources/Private/Partials/Product/CartForm.html
cart_products/Resources/Private/Templates/Product/Show.html
```

**Comment by Hobokens** [comment]
Implementing the  [bugfix](https://github.com/extcode/cart/pull/537) solves the problem.
