### ISSUE TITLE
`add_to_cart.js` is twice in `CartForm.html`

### ISSUE THREAD

**Issue by rintisch** [extcode/cart_products#183]
## Bug Report

**Current Behavior**
`add_to_cart.js` is added twice in https://github.com/extcode/cart_products/blob/4997401e68238209580c9adcb90c1f8d3e7392bf/Resources/Private/Partials/Product/CartForm.html

**Expected behavior/output**
No double inserted JS of same file

**Environment**
- TYPO3 version(s): 12.4
- cart version: main
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Remove line 58

**Comment by format-gmbh** [comment]
Das Problem in Zeile 58 ist, dass das Javascript File aus dem falschen Ordner geladen werden soll. Deshalb funktioniert das Include beim 2. mal nicht.
```
<f:asset.script identifier="add-to-cart" src="EXT:cart/Resources/Public/JavaScripts/add_to_cart.js" />
```
