### ISSUE TITLE
undefined array key in ProductRepository if "orderBy" without "orderDirection"

### ISSUE THREAD

**Issue by kanow** [extcode/cart_products#185]
## Bug Report

**Current Behavior**
Exception in frontend of `cartproducts_products` plugin if `orderBy` in  flexform configuration is used but without setting `orderDirection`.

```
Whoops\Exception\ErrorException thrown with message "Undefined array key 1"
#191 Whoops\Exception\ErrorException in /app/vendor/extcode/cart-products/Classes/Domain/Repository/Product/ProductRepository.php:76
```

**Expected behavior/output**
List of products sorted by choosed ordering, asc.

**Environment**
- TYPO3 version(s): 12.4.14
- cart version: 9.0.0
- cart_products: dev-main
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: local docker environment apache2

**Possible Solution**
Set `oderDirection` in flexform will fix it and the products are shown. But better should be fixed in code in line 76 of `ProductRepository.php`.
`$orderDirection` should have a default (key and value) if not set by flexform configuration.

**Comment by rintisch** [comment]
@kanow I cannot recreate your bug. The `ProductRepository` cares already about a default value:

https://github.com/extcode/cart_products/blob/7a072782269eeb3ac75689730ee993b15297fcaa/Classes/Domain/Repository/Product/ProductRepository.php#L75-L88

→ If no value is set it will be sorted ascending.

I will close the ticket but you're welcome to reopen it in case I am wrong.

**Comment by kanow** [comment]
Error (E_WARNING) still exists. Maybe important to reproducing this: PHP 8.2, Development Context
![image](https://github.com/user-attachments/assets/c465a03a-852b-4880-9f9b-3545db05af27)

**Comment by rintisch** [comment]
Thanks for the feedback. True, I had wrong settings. Sorry!

The problem is the array destructuring which fails when no direction is given.

**Comment by extcode** [comment]
I filled up the trim explode with the default ordering `'asc'`.
