### ISSUE TITLE
Fix in DatamapDataHandlerHook is missing in current main branch

### ISSUE THREAD

**Issue by kanow** [extcode/cart_products#189]
This PR was already merged in main to fix php8 warning.

https://github.com/extcode/cart_products/pull/122/files#diff-2729950a61bc6a5b0b5e0aa436007e52c5c6f2bf2a4a0c3365d2ae8328e6ce04

But in current main branch those fix is missing. Error is shown again on creating new content elements in backend.

**Comment by rintisch** [comment]
True. Weird. Must have been some rebasing. I will create a PR.
