### ISSUE TITLE
Undefined array key exception in UpgradeWizard

### ISSUE THREAD

**Issue by extcode** [extcode/cart_products#226]
## Bug Report by Slack

**Current Behavior**
The UpgradeWizard terminates with: `PHP Warning: Undefined array key "cartproducts_showproduct,list" in /www/htdocs/.../typo3conf/ext/cart_products/Classes/Updates/SwitchableControllerActionsPluginUpdater.php line 168` exception

**Expected behavior/output**
UpgradeWizard migrate all cart-products plugins.

**Environment**
- TYPO3 version(s): 12.4.x
- cart-products version: 5.0.1

**Comment by extcode** [comment]
As far as I can see the error occurs only if the instance have at least one plugin that has to migrate to `cartproducts_showproduct`, because there is no flexform registered for this plugin and therefore no registartion in the TCA column `pi_flexform`.

**Comment by rintisch** [comment]
@extcode I guess this can be closed?
