### ISSUE TITLE
Installing cart_products 5.0.4 I'm getting exception "Given select field item list was not found."

### ISSUE THREAD

**Issue by Poepp** [extcode/cart_products#233]
## Bug Report

**Current Behavior**
When installing latest version 5.0.4 of card_products, I get "Given select field item list was not found." This problem can be solved by just commenting out the following lines in "cart_products/Configuration/TCA/Overrides/sys_reaction.php"

// Add the custom type to the type select
ExtensionManagementUtility::addTcaSelectItem(
    'sys_reaction',
    'reaction_type',
    [
        'label' => UpdateStockReaction::getDescription(),
        'value' => UpdateStockReaction::getType(),
        'icon' => UpdateStockReaction::getIconIdentifier(),
    ]
);

**Environment**
- TYPO3 version(s): [12.4.22]
- cart version: [9.0.3]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]

**Additional context**
I'm not sure if this is a problem of my environment or if this is a bug. At least according to the official documentation the approach followed in card_products seems fine (https://docs.typo3.org/c/typo3/cms-reactions/main/en-us/Reactions/CustomReactionType/Index.html#custom-reaction-type-1). However, I'm not able to find a solution or workaround for this topic.

Thanks for any feedback or insights
Florian

**Comment by extcode** [comment]
This is related to non composer mode. In composer mode the typo3/cms-reaction will be installed by the defined dependencies.
I'll remove the hard dependency (for both) to typo3/cms-reaction and add some conditions. I think the reactions could be optional.

**Comment by extcode** [comment]
Please check if version v5.0.5 fixes the problem. I have provided typo3/cms-reactions as an optional extension, as the Reactions feature is not required for proper functionality. Furthermore, the example is not yet fully implemented.

**Comment by Poepp** [comment]
Thanks a lot for the very quick response - I will give it a try this evening!

**Comment by Poepp** [comment]
I just installed the latest version into my environment and the problem has successfully been resolved! I double checked that the new files have been properly installed and the changes are available.
Thanks again and I will close this issue!
