### ISSUE TITLE
Cart Product not extendable

### ISSUE THREAD

**Issue by MarcKoester** [extcode/cart_products#33]
I want to update from cart 4.8 to cart 5.1 and cart_products 1.0.
 We have extended the Extcode\Cart\Domain\Model\Cart\Product to add a company, so we can display different terms and conditions for different companies.

The Cart Product is currently created directly without the objectManager:

https://github.com/extcode/cart_products/blob/eb0db20cb06b068c8869f91fe7fc99279ab59600/Classes/Utility/ProductUtility.php#L137-L147

Is it possible to use the objectManager to initialize the product? As it was in 4.8?

**Comment by extcode** [comment]
I think you can extend the product class as before and use the SignalSlot some code lines later to add your value to $cartProduct.

https://github.com/extcode/cart_products/blob/eb0db20cb06b068c8869f91fe7fc99279ab59600/Classes/Utility/ProductUtility.php#L169-L184

**Comment by extcode** [comment]
Is the property additional of the $cartProduct an option? This field can used for own stuff.

**Comment by MarcKoester** [comment]
Yes that would be an option. I will use the property additional then.
Thanks for your help,
