### ISSUE TITLE
Cant overwrite RootPaths

### ISSUE THREAD

**Issue by sevensix** [extcode/cart_products#39]
I am using the cart for Typo3 8.7. I cant overwrite the template/Partials/Layouts-RootPaths. When I set new Paths to my Extensionfolder the new Path to my files does not show up in the TS-Objetctbrowser.
Any idea to set this right, to use my own templates?

**Comment by extcode** [comment]
Can you show me, how your TypoScript configuration looks like?

**Comment by sevensix** [comment]
here is my ts: 

![cart3](https://user-images.githubusercontent.com/4035097/57407886-876c1380-71e4-11e9-9a9c-7afdf13d5c8b.JPG)

and here are screenshots of the template-Analyse (showing, my ts is loaded)  and the TS-Object-Browser (showing, my ts is not overwriting the cart_products rootpaths)

and the frontent shows me, that my templates are not used...

![cart2](https://user-images.githubusercontent.com/4035097/57407669-057bea80-71e4-11e9-9d84-3eb91bc3a7e1.JPG)
![cart](https://user-images.githubusercontent.com/4035097/57407670-057bea80-71e4-11e9-8b87-d4ca24157944.JPG)

**Comment by sevensix** [comment]
And i tried different ordering of including the templates. (put mine in front of the cart_products and behind..

![cart4](https://user-images.githubusercontent.com/4035097/57408029-e2056f80-71e4-11e9-91a6-ee1798d41b35.JPG)

**Comment by extcode** [comment]
I think this should work somehow. It's no cart_products specific in loading paths for layouts, templates and partials. Do the TypoScript Object Browser shows an error, so the path configuration after this error will be ignored? Can you test your path configuration in the setup field of your TypoScript template?

**Comment by sevensix** [comment]
i am a bit closer now. As i missed a bracket somewhere in my ts, now the objectbrowsers shows the right configuration so you can close this. sorry.
