### ISSUE TITLE
No posibillity to create new be_variant_attribute_option

### ISSUE THREAD

**Issue by herrhamann** [extcode/cart_products#59]
Hi,

since version 2.0.0 it isn't possible to create a new "be_variant_attribute_option". The button "Create new" is not shown anymore.

Greets
Alex

**Comment by johannesabrunner** [comment]
For me this wasn't possible at any time. I always have to add variant options directly into the corresponding table in the database. This works fine for me... always wondered if I am the only one with this problem ... should say that I am running the BE in german language

**Comment by Starraider** [comment]
In Version 2.1.0 this problem still exists.
