### ISSUE TITLE
Compatibility to TYPO3 10.4

### ISSUE THREAD

**Issue by Cretection** [extcode/cart_products#66]
Are there already plans for compatibility with TYPO3 10.4?

**Comment by extcode** [comment]
Yes. I'm currently working on extcode/cart and extcode/cart-books. extcode/cart-products follows after.

**Comment by Cretection** [comment]
I have started to update the extension as far as I could. At the moment I am hanging on the frontend-error missing tx_cartproducts_domain_model_ttcontent.
Then I'll wait. Thanks a lot

Thanks for your work on cart!

**Comment by Cretection** [comment]
Done
