### ISSUE TITLE
Add Products from Cart in List View

### ISSUE THREAD

**Issue by X-Tender** [extcode/cart_products#73]
I followed this instruction to allow adding Products to cart from the List view
https://docs.typo3.org/p/extcode/cart-products/2.4/en-us/Changelog/2.3/Feature-70-AddProductsToCartFromListView.html
but then I got the error

`There is more than one plugin that can handle this request (Extension: "CartProducts", Controller: "Product", action: "show"). Please specify "pluginName" argument`

**Comment by X-Tender** [comment]
It seems like its a typo3 bug -_-
https://forge.typo3.org/issues/91249

**Comment by X-Tender** [comment]
What's odd on this problem is that it complains about the `show` action and in the `lib.cartProduct` you set the `showForm` action.

**Comment by X-Tender** [comment]
Seems like its related to this issue https://forge.typo3.org/issues/88399

**Comment by X-Tender** [comment]
Ok because if the bug I took a look why it worked in the previous version before the recomendation to use it via cObject and when I put that fluid snippet in my list templates it works.
```
<f:if condition="{settings.cart.pid}">
   <f:render partial="Product/CartForm" arguments="{product: product, pid: settings.cart.pid}"/>
</f:if>
```

**Comment by rintisch** [comment]
Tested in current main (coming v5) under TYPO3 v12 and it works. Due to this I test this issue.

Thanks for your input!
