### ISSUE TITLE
Cant copy pages

### ISSUE THREAD

**Issue by typo3rel** [extcode/cart_products#75]
when i try to copy a page the error follows:
`
2: SQL error: 'Incorrect integer value: '' for column `db`.`pages`.`cart_products_product` at row 1' (pages:NEW5f3cdbfe7a670551125942)`

**Comment by Cretection** [comment]
Me too.
`2: SQL error: 'Incorrect integer value: '' for column `db`.`pages`.`cart_products_product` at row 1' (pages:NEW60095c2e16267012172973)`

What is the function of the "cart_products_product" line in "pages"? Is it necessary at all?
