### ISSUE TITLE
AddToCartFinisher

### ISSUE THREAD

**Issue by freeATweb** [extcode/cart_products#77]
Hello,

I'm getting an error if a product is added to the cart   (ext:cart & ext:cart_products):

Fatal error: Declaration of Extcode\CartProducts\Domain\Finisher\Cart\AddToCartFinisher::checkAvailability(TYPO3\CMS\Extbase\Mvc\Web\Request $request, Extcode\Cart\Domain\Model\Cart\Product $cartProduct, Extcode\Cart\Domain\Model\Cart\Cart $cart, string $mode = 'update'): Extcode\Cart\Domain\Model\Dto\AvailabilityResponse must be compatible with Extcode\Cart\Domain\Finisher\Cart\AddToCartFinisherInterface::checkAvailability(TYPO3\CMS\Extbase\Mvc\Request $request, Extcode\Cart\Domain\Model\Cart\Product $cartProduct, Extcode\Cart\Domain\Model\Cart\Cart $cart): Extcode\Cart\Domain\Model\Dto\AvailabilityResponse in /html/typo3/typo3conf/ext/cart_products/Classes/Domain/Finisher/Cart/AddToCartFinisher.php on line 46

Can you please help me?

Thanks

Best Regards

**Comment by rintisch** [comment]
This issue is quite old, the `AddToCartFinisher` does no longer exist. Is it okay to close this issue?

**Comment by freeATweb** [comment]
that' ok 👍Von Unterwegs gesendet.
-------- Ursprüngliche Nachricht --------Von: "Gerald R." ***@***.***> Datum: 11.06.24  18:24  (GMT+01:00) An: extcode/cart_products ***@***.***> Cc: freeATweb ***@***.***>, Author ***@***.***> Betreff: Re: [extcode/cart_products] AddToCartFinisher (#77) 
This issue is quite old, the AddToCartFinisher does no longer exist. Is it okay to close this issue?

**Comment by rintisch** [comment]
Thank you for the feedback!
