### ISSUE TITLE
Category single pid error

### ISSUE THREAD

**Issue by stephangrass** [extcode/cart_products#79]
As soon as I try to use the category-feature “Cart: Page where Products of this category are shown.“, I will get the error “Call to a member function getUriBuilder() on null” when calling the details page.

**Comment by stephangrass** [comment]
OK. In cart_products/Classes/ViewHelpers/CanonicalTagViewHelper.php two removed methods are still used:

$this->renderingContext and getPageRenderer()

Changing
`$uriBuilder = $this->controllerContext->getUriBuilder();`
to
`$uriBuilder = $this->renderingContext->getControllerContext()->getUriBuilder();`

and
`    protected function getPageRenderer()`
`    {`
`        if ('FE' === TYPO3_MODE && is_callable([$this->getTypoScriptFrontendController(), 'getPageRenderer'])) {`
`            return $this->getTypoScriptFrontendController()->getPageRenderer();`
`        } else {`
`            return GeneralUtility::makeInstance('TYPO3\CMS\Core\Page\PageRenderer');`
`        }`
`    }`

to
`    protected function getTypoScriptFrontendController()`
`    {`
`        return $GLOBALS['TSFE'];`
`    }`
will work.

**Comment by rintisch** [comment]
This issue is quite old. Does this error still occur for you (have not tested because of missing time). Could you test with 5.x-dev (which is compatible for v12)?

**Comment by rintisch** [comment]
I will close this issue now due to missing feedback. You're welcome to reopen it if needed.
