### ISSUE TITLE
Refactor ext_typoscript_constants.typoscript and ext_typoscript_setup.typoscript 

### ISSUE THREAD

**Issue by Freshmeat-ch** [extcode/cart_products#80]
into Configuration/TypoScript/constants.typoscript and Configuration/TypoScript/setup.typoscript 
otherwise its impossible to overwrite module.tx_cartproducts settings (i.E. to change the currency in the backend-module) with imports from an other extension (template-ext).

**Comment by rintisch** [comment]
Both files do no longer exist above v2, so this issue can be closed.
