### ISSUE TITLE
Class self does not exist.

### ISSUE THREAD

**Issue by machwatt** [extcode/cart_products#88]
I got an error rendering the product list.

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1278450972: Class self does not exist. Reflection failed. | TYPO3\CMS\Extbase\Reflection\Exception\UnknownClassException thrown in file /xyz/htdocs/public/typo3/sysext/extbase/Classes/Reflection/ReflectionService.php in line 125.

I hunted it down to the self reference in some methods in the `Product` class. Why is it `self` here and not `addRelatedProduct(Product $relatedProduct)`. After testing it with replacing self by Product it works. Is there any reason for that, that i dont get yet? 

Anyways, thx for your work and time for this project.

https://github.com/extcode/cart_products/blob/c5fe431441191e4e63269b4d2e26f6104dfb6d03/Classes/Domain/Model/Product/Product.php#L962

**Comment by rintisch** [comment]
This was solved with https://github.com/extcode/cart_products/commit/b39dd8127ea405c31f53e373ae0a8a50f4ae3c3f and can be closed.
